import type { BaseBlock, ElementBlock } from '@/types/edit'
import { setFormData } from '@/utils'

export const baseBlock: BaseBlock[] = [
  {
    id: '',
    code: 'image',
    name: '图片',
    icon: 'image',
    formData: {},
  },
  {
    id: '',
    code: 'video',
    name: '视频',
    icon: 'video',
    formData: {},
  },
  {
    id: '',
    code: 'textarea',
    name: '文本',
    icon: 'text',
    formData: {},
  },
  {
    id: '',
    name: '幻灯片',
    code: 'slide',
    icon: 'swiper',
    formData: {},
  },
  {
    id: '',
    name: '留白',
    code: 'blank',
    icon: 'blank',
    formData: {},
  },
]

export const seniorBlocks: BaseBlock[] = [
  {
    id: '',
    name: '多行',
    code: 'row',
    icon: 'row',
    nested: true,
    children: [[], []],
    formData: {},
  },
  {
    id: '',
    name: '多列',
    code: 'column',
    icon: 'column',
    nested: true,
    children: [[], []],
    formData: {},
  },
  {
    id: '',
    name: '画布',
    code: 'canvas',
    icon: 'canvas',
    nested: true,
    children: [[]],
    formData: {},
  },
]

export const canvasBlocks: ElementBlock[] = [
  {
    id: '',
    code: 'ElButton',
    name: '按钮',
    icon: 'button',
    formData: {
      type: setFormData('primary'),
      content: setFormData('button'),
      size: setFormData(''),
    },
    type: 'el',
  },
  {
    id: '',
    code: 'ElInput',
    name: '输入框',
    icon: 'input',
    formData: {
      type: setFormData('text'),
      placeholder: setFormData(''),
      clearable: setFormData(true),
      'show-password': setFormData(false),
      content: setFormData(''),
    },
    type: 'el',
  },
  {
    id: '',
    code: 'eldropdown',
    name: '下拉框',
    icon: 'dropdown',
    formData: {},
  },
  {
    id: '',
    code: 'elblock',
    name: '日期',
    icon: 'data',
    formData: {},
  },
  {
    id: '',
    code: 'ElSwitch',
    name: '开关',
    icon: 'switch',
    formData: {
      loading: setFormData(false),
      content: setFormData(false),
      size: setFormData(''),
      width: setFormData(''),
      disabled: setFormData(false),
      'active-color': setFormData(''),
      'inactive-color': setFormData(''),
    },
    type: 'el',
  },
  {
    id: '',
    code: 'ElSlide',
    name: '滑块',
    icon: 'slide',
    formData: {
      content: setFormData(0),
      min: setFormData(0),
      max: setFormData(10),
      disabled: setFormData(false),
      step: setFormData(1),
      'show-input': setFormData(false),
      'show-stops': setFormData(false),
      vertical: setFormData(false),
    },
    type: 'el',
  },
  {
    id: '',
    code: 'elmenu',
    name: '菜单',
    icon: 'menu',
    formData: {},
  },
  {
    id: '',
    code: 'eltabs',
    name: '标签页',
    icon: 'tabs',
    formData: {},
  },
  {
    id: '',
    code: 'elbreadcrumb',
    name: '面包屑',
    icon: 'breadcrumb',
    formData: {},
  },
  {
    id: '',
    code: 'eldialog',
    name: '对话框',
    icon: 'dialog',
    formData: {},
  },
]
