/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Blank: typeof import('./src/components/blank/index.vue')['default']
    Canvas: typeof import('./src/components/canvas/index.vue')['default']
    Carousel: typeof import('./src/components/carousel/index.vue')['default']
    Column: typeof import('./src/components/column/index.vue')['default']
    Customcode: typeof import('./src/components/customcode/index.vue')['default']
    Elblock: typeof import('./src/components/elblock/index.vue')['default']
    Elbreadcrumb: typeof import('./src/components/elbreadcrumb/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    Elcard: typeof import('./src/components/elcard/index.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    Eldialog: typeof import('./src/components/eldialog/index.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    Eldropdown: typeof import('./src/components/eldropdown/index.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Elmenu: typeof import('./src/components/elmenu/index.vue')['default']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    Elnotification: typeof import('./src/components/elnotification/index.vue')['default']
    Elpagination: typeof import('./src/components/elpagination/index.vue')['default']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Elprogress: typeof import('./src/components/elprogress/index.vue')['default']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Eltable: typeof import('./src/components/eltable/index.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    Eltabs: typeof import('./src/components/eltabs/index.vue')['default']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Empty: typeof import('./src/components/empty/index.vue')['default']
    Image: typeof import('./src/components/image/index.vue')['default']
    Link: typeof import('./src/components/link/index.vue')['default']
    MenuItem: typeof import('./src/components/elmenu/menu-item.vue')['default']
    Row: typeof import('./src/components/row/index.vue')['default']
    Textarea: typeof import('./src/components/textarea/index.vue')['default']
    Video: typeof import('./src/components/video/index.vue')['default']
  }
}
